// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: cmd/odas/grpc/portrait/portrait.proto

package portrait

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	grpc "odas/cmd/odas/grpc"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FellowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Province string                                   `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
}

func (x *FellowRequest) Reset() {
	*x = FellowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FellowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FellowRequest) ProtoMessage() {}

func (x *FellowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FellowRequest.ProtoReflect.Descriptor instead.
func (*FellowRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{0}
}

func (x *FellowRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FellowRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

type AgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Province string                                   `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	Unknown  bool                                     `protobuf:"varint,3,opt,name=unknown,proto3" json:"unknown,omitempty"`
}

func (x *AgeRequest) Reset() {
	*x = AgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeRequest) ProtoMessage() {}

func (x *AgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeRequest.ProtoReflect.Descriptor instead.
func (*AgeRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{1}
}

func (x *AgeRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AgeRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AgeRequest) GetUnknown() bool {
	if x != nil {
		return x.Unknown
	}
	return false
}

type AgeSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *AgeSummaryTotal  `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*AgeSummaryList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AgeSummaryResponse) Reset() {
	*x = AgeSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeSummaryResponse) ProtoMessage() {}

func (x *AgeSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeSummaryResponse.ProtoReflect.Descriptor instead.
func (*AgeSummaryResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{2}
}

func (x *AgeSummaryResponse) GetTotal() *AgeSummaryTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *AgeSummaryResponse) GetList() []*AgeSummaryList {
	if x != nil {
		return x.List
	}
	return nil
}

type AgeSummaryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgeGroup string `protobuf:"bytes,1,opt,name=ageGroup,proto3" json:"ageGroup,omitempty"`
	Female   int64  `protobuf:"varint,2,opt,name=female,proto3" json:"female,omitempty"`
	Male     int64  `protobuf:"varint,3,opt,name=male,proto3" json:"male,omitempty"`
}

func (x *AgeSummaryList) Reset() {
	*x = AgeSummaryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeSummaryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeSummaryList) ProtoMessage() {}

func (x *AgeSummaryList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeSummaryList.ProtoReflect.Descriptor instead.
func (*AgeSummaryList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{3}
}

func (x *AgeSummaryList) GetAgeGroup() string {
	if x != nil {
		return x.AgeGroup
	}
	return ""
}

func (x *AgeSummaryList) GetFemale() int64 {
	if x != nil {
		return x.Female
	}
	return 0
}

func (x *AgeSummaryList) GetMale() int64 {
	if x != nil {
		return x.Male
	}
	return 0
}

type AgeSummaryTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Male   int64 `protobuf:"varint,2,opt,name=male,proto3" json:"male,omitempty"`
	Female int64 `protobuf:"varint,3,opt,name=female,proto3" json:"female,omitempty"`
}

func (x *AgeSummaryTotal) Reset() {
	*x = AgeSummaryTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeSummaryTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeSummaryTotal) ProtoMessage() {}

func (x *AgeSummaryTotal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeSummaryTotal.ProtoReflect.Descriptor instead.
func (*AgeSummaryTotal) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{4}
}

func (x *AgeSummaryTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AgeSummaryTotal) GetMale() int64 {
	if x != nil {
		return x.Male
	}
	return 0
}

func (x *AgeSummaryTotal) GetFemale() int64 {
	if x != nil {
		return x.Female
	}
	return 0
}

type FellowListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count int64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Rate  float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *FellowListResponse) Reset() {
	*x = FellowListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FellowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FellowListResponse) ProtoMessage() {}

func (x *FellowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FellowListResponse.ProtoReflect.Descriptor instead.
func (*FellowListResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{5}
}

func (x *FellowListResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FellowListResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FellowListResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type FellowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*FellowListResponse `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *FellowResponse) Reset() {
	*x = FellowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FellowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FellowResponse) ProtoMessage() {}

func (x *FellowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FellowResponse.ProtoReflect.Descriptor instead.
func (*FellowResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{6}
}

func (x *FellowResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FellowResponse) GetList() []*FellowListResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type PaymentMethodListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel string  `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Total   int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Rate    float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *PaymentMethodListResponse) Reset() {
	*x = PaymentMethodListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentMethodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethodListResponse) ProtoMessage() {}

func (x *PaymentMethodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethodListResponse.ProtoReflect.Descriptor instead.
func (*PaymentMethodListResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentMethodListResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentMethodListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaymentMethodListResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type PaymentMethodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*PaymentMethodListResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PaymentMethodResponse) Reset() {
	*x = PaymentMethodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethodResponse) ProtoMessage() {}

func (x *PaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*PaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentMethodResponse) GetList() []*PaymentMethodListResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type CityRankRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Compare  *grpc.PassedCompareTimeSpanV4Request     `protobuf:"bytes,2,opt,name=compare,proto3" json:"compare,omitempty"`
	Province string                                   `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	Limit    int64                                    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Unknown  bool                                     `protobuf:"varint,5,opt,name=unknown,proto3" json:"unknown,omitempty"`
}

func (x *CityRankRequest) Reset() {
	*x = CityRankRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityRankRequest) ProtoMessage() {}

func (x *CityRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityRankRequest.ProtoReflect.Descriptor instead.
func (*CityRankRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{9}
}

func (x *CityRankRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CityRankRequest) GetCompare() *grpc.PassedCompareTimeSpanV4Request {
	if x != nil {
		return x.Compare
	}
	return nil
}

func (x *CityRankRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CityRankRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CityRankRequest) GetUnknown() bool {
	if x != nil {
		return x.Unknown
	}
	return false
}

type CityRankListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City             string  `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Total            int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	CompareTotalRate float64 `protobuf:"fixed64,3,opt,name=compareTotalRate,proto3" json:"compareTotalRate,omitempty"`
	Rate             float64 `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *CityRankListResponse) Reset() {
	*x = CityRankListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityRankListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityRankListResponse) ProtoMessage() {}

func (x *CityRankListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityRankListResponse.ProtoReflect.Descriptor instead.
func (*CityRankListResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{10}
}

func (x *CityRankListResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CityRankListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CityRankListResponse) GetCompareTotalRate() float64 {
	if x != nil {
		return x.CompareTotalRate
	}
	return 0
}

func (x *CityRankListResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type CityRankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*CityRankListResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *CityRankResponse) Reset() {
	*x = CityRankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityRankResponse) ProtoMessage() {}

func (x *CityRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityRankResponse.ProtoReflect.Descriptor instead.
func (*CityRankResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{11}
}

func (x *CityRankResponse) GetList() []*CityRankListResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type ProvinceRankRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Compare *grpc.PassedCompareTimeSpanV4Request     `protobuf:"bytes,2,opt,name=compare,proto3" json:"compare,omitempty"`
	Limit   int64                                    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Unknown bool                                     `protobuf:"varint,4,opt,name=unknown,proto3" json:"unknown,omitempty"`
}

func (x *ProvinceRankRequest) Reset() {
	*x = ProvinceRankRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvinceRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvinceRankRequest) ProtoMessage() {}

func (x *ProvinceRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvinceRankRequest.ProtoReflect.Descriptor instead.
func (*ProvinceRankRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{12}
}

func (x *ProvinceRankRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ProvinceRankRequest) GetCompare() *grpc.PassedCompareTimeSpanV4Request {
	if x != nil {
		return x.Compare
	}
	return nil
}

func (x *ProvinceRankRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ProvinceRankRequest) GetUnknown() bool {
	if x != nil {
		return x.Unknown
	}
	return false
}

type ProvinceRankListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Province         string  `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	Total            int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	CompareTotalRate float64 `protobuf:"fixed64,3,opt,name=compareTotalRate,proto3" json:"compareTotalRate,omitempty"`
	Rate             float64 `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *ProvinceRankListResponse) Reset() {
	*x = ProvinceRankListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvinceRankListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvinceRankListResponse) ProtoMessage() {}

func (x *ProvinceRankListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvinceRankListResponse.ProtoReflect.Descriptor instead.
func (*ProvinceRankListResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{13}
}

func (x *ProvinceRankListResponse) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ProvinceRankListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProvinceRankListResponse) GetCompareTotalRate() float64 {
	if x != nil {
		return x.CompareTotalRate
	}
	return 0
}

func (x *ProvinceRankListResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type ProvinceRankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ProvinceRankListResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ProvinceRankResponse) Reset() {
	*x = ProvinceRankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvinceRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvinceRankResponse) ProtoMessage() {}

func (x *ProvinceRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvinceRankResponse.ProtoReflect.Descriptor instead.
func (*ProvinceRankResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{14}
}

func (x *ProvinceRankResponse) GetList() []*ProvinceRankListResponse {
	if x != nil {
		return x.List
	}
	return nil
}

// 定义对比年龄性别请求参数 AgeCompareRequest
type AgeCompareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Compare  *grpc.PassedCompareTimeSpanV4Request     `protobuf:"bytes,2,opt,name=compare,proto3" json:"compare,omitempty"`
	Unknown  bool                                     `protobuf:"varint,3,opt,name=unknown,proto3" json:"unknown,omitempty"`
	Province string                                   `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
}

func (x *AgeCompareRequest) Reset() {
	*x = AgeCompareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeCompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeCompareRequest) ProtoMessage() {}

func (x *AgeCompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeCompareRequest.ProtoReflect.Descriptor instead.
func (*AgeCompareRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{15}
}

func (x *AgeCompareRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AgeCompareRequest) GetCompare() *grpc.PassedCompareTimeSpanV4Request {
	if x != nil {
		return x.Compare
	}
	return nil
}

func (x *AgeCompareRequest) GetUnknown() bool {
	if x != nil {
		return x.Unknown
	}
	return false
}

func (x *AgeCompareRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

// 定义对比年龄性别响应体 AgeCompareResponse
type AgeCompareSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total       *AgeCompareSummaryTotal `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	List        []*AgeSummaryList       `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	CompareList []*AgeSummaryList       `protobuf:"bytes,3,rep,name=compareList,proto3" json:"compareList,omitempty"`
}

func (x *AgeCompareSummaryResponse) Reset() {
	*x = AgeCompareSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeCompareSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeCompareSummaryResponse) ProtoMessage() {}

func (x *AgeCompareSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeCompareSummaryResponse.ProtoReflect.Descriptor instead.
func (*AgeCompareSummaryResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{16}
}

func (x *AgeCompareSummaryResponse) GetTotal() *AgeCompareSummaryTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *AgeCompareSummaryResponse) GetList() []*AgeSummaryList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AgeCompareSummaryResponse) GetCompareList() []*AgeSummaryList {
	if x != nil {
		return x.CompareList
	}
	return nil
}

type AgeCompareSummaryTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total         int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	CompareTotal  int64 `protobuf:"varint,2,opt,name=compareTotal,proto3" json:"compareTotal,omitempty"`
	Male          int64 `protobuf:"varint,3,opt,name=male,proto3" json:"male,omitempty"`
	CompareMale   int64 `protobuf:"varint,4,opt,name=compareMale,proto3" json:"compareMale,omitempty"`
	Female        int64 `protobuf:"varint,5,opt,name=female,proto3" json:"female,omitempty"`
	CompareFemale int64 `protobuf:"varint,6,opt,name=compareFemale,proto3" json:"compareFemale,omitempty"`
}

func (x *AgeCompareSummaryTotal) Reset() {
	*x = AgeCompareSummaryTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeCompareSummaryTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeCompareSummaryTotal) ProtoMessage() {}

func (x *AgeCompareSummaryTotal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeCompareSummaryTotal.ProtoReflect.Descriptor instead.
func (*AgeCompareSummaryTotal) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP(), []int{17}
}

func (x *AgeCompareSummaryTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AgeCompareSummaryTotal) GetCompareTotal() int64 {
	if x != nil {
		return x.CompareTotal
	}
	return 0
}

func (x *AgeCompareSummaryTotal) GetMale() int64 {
	if x != nil {
		return x.Male
	}
	return 0
}

func (x *AgeCompareSummaryTotal) GetCompareMale() int64 {
	if x != nil {
		return x.CompareMale
	}
	return 0
}

func (x *AgeCompareSummaryTotal) GetFemale() int64 {
	if x != nil {
		return x.Female
	}
	return 0
}

func (x *AgeCompareSummaryTotal) GetCompareFemale() int64 {
	if x != nil {
		return x.CompareFemale
	}
	return 0
}

var File_cmd_odas_grpc_portrait_portrait_proto protoreflect.FileDescriptor

var file_cmd_odas_grpc_portrait_portrait_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61,
	0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x0d, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x22,
	0x81, 0x01, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e,
	0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x22, 0x61, 0x0a, 0x12, 0x41, 0x67, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x41, 0x67, 0x65, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x41, 0x67, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x0e, 0x41, 0x67, 0x65, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x61, 0x6c, 0x65,
	0x22, 0x53, 0x0a, 0x0f, 0x41, 0x67, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66,
	0x65, 0x6d, 0x61, 0x6c, 0x65, 0x22, 0x52, 0x0a, 0x12, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x0e, 0x46, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x19, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x15, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0xd7, 0x01, 0x0a, 0x0f, 0x43, 0x69, 0x74, 0x79, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x50, 0x61, 0x73, 0x73,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65,
	0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e,
	0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x22, 0x80,
	0x01, 0x0a, 0x14, 0x43, 0x69, 0x74, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x22, 0x3d, 0x0a, 0x10, 0x43, 0x69, 0x74, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0xbf, 0x01, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x50, 0x61, 0x73, 0x73,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65,
	0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e,
	0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x22, 0x8c, 0x01, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52,
	0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x22, 0x45, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xc3, 0x01, 0x0a, 0x11, 0x41, 0x67, 0x65,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e,
	0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x22, 0xa2,
	0x01, 0x0a, 0x19, 0x41, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x41, 0x67,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x67, 0x65, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x67, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0xc6, 0x01, 0x0a, 0x16, 0x41, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x4d, 0x61, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x4d, 0x61, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x66, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x32, 0xe4, 0x02, 0x0a,
	0x0f, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x30, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x0b,
	0x2e, 0x41, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x41, 0x67,
	0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x2b, 0x0a, 0x06, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x0e, 0x2e, 0x46,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x46,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x0e, 0x2e, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08, 0x43, 0x69,
	0x74, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x10, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52,
	0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x2e,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x61,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x11,
	0x41, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x12, 0x12, 0x2e, 0x41, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x41, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x63, 0x6d, 0x64, 0x2f,
	0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x72, 0x61,
	0x69, 0x74, 0x3b, 0x70, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cmd_odas_grpc_portrait_portrait_proto_rawDescOnce sync.Once
	file_cmd_odas_grpc_portrait_portrait_proto_rawDescData = file_cmd_odas_grpc_portrait_portrait_proto_rawDesc
)

func file_cmd_odas_grpc_portrait_portrait_proto_rawDescGZIP() []byte {
	file_cmd_odas_grpc_portrait_portrait_proto_rawDescOnce.Do(func() {
		file_cmd_odas_grpc_portrait_portrait_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_odas_grpc_portrait_portrait_proto_rawDescData)
	})
	return file_cmd_odas_grpc_portrait_portrait_proto_rawDescData
}

var file_cmd_odas_grpc_portrait_portrait_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_cmd_odas_grpc_portrait_portrait_proto_goTypes = []interface{}{
	(*FellowRequest)(nil),                           // 0: FellowRequest
	(*AgeRequest)(nil),                              // 1: AgeRequest
	(*AgeSummaryResponse)(nil),                      // 2: AgeSummaryResponse
	(*AgeSummaryList)(nil),                          // 3: AgeSummaryList
	(*AgeSummaryTotal)(nil),                         // 4: AgeSummaryTotal
	(*FellowListResponse)(nil),                      // 5: FellowListResponse
	(*FellowResponse)(nil),                          // 6: FellowResponse
	(*PaymentMethodListResponse)(nil),               // 7: PaymentMethodListResponse
	(*PaymentMethodResponse)(nil),                   // 8: PaymentMethodResponse
	(*CityRankRequest)(nil),                         // 9: CityRankRequest
	(*CityRankListResponse)(nil),                    // 10: CityRankListResponse
	(*CityRankResponse)(nil),                        // 11: CityRankResponse
	(*ProvinceRankRequest)(nil),                     // 12: ProvinceRankRequest
	(*ProvinceRankListResponse)(nil),                // 13: ProvinceRankListResponse
	(*ProvinceRankResponse)(nil),                    // 14: ProvinceRankResponse
	(*AgeCompareRequest)(nil),                       // 15: AgeCompareRequest
	(*AgeCompareSummaryResponse)(nil),               // 16: AgeCompareSummaryResponse
	(*AgeCompareSummaryTotal)(nil),                  // 17: AgeCompareSummaryTotal
	(*grpc.PassedTimeSpanByOrderTypeV4Request)(nil), // 18: PassedTimeSpanByOrderTypeV4Request
	(*grpc.PassedCompareTimeSpanV4Request)(nil),     // 19: PassedCompareTimeSpanV4Request
}
var file_cmd_odas_grpc_portrait_portrait_proto_depIdxs = []int32{
	18, // 0: FellowRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	18, // 1: AgeRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	4,  // 2: AgeSummaryResponse.total:type_name -> AgeSummaryTotal
	3,  // 3: AgeSummaryResponse.list:type_name -> AgeSummaryList
	5,  // 4: FellowResponse.list:type_name -> FellowListResponse
	7,  // 5: PaymentMethodResponse.list:type_name -> PaymentMethodListResponse
	18, // 6: CityRankRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	19, // 7: CityRankRequest.compare:type_name -> PassedCompareTimeSpanV4Request
	10, // 8: CityRankResponse.list:type_name -> CityRankListResponse
	18, // 9: ProvinceRankRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	19, // 10: ProvinceRankRequest.compare:type_name -> PassedCompareTimeSpanV4Request
	13, // 11: ProvinceRankResponse.list:type_name -> ProvinceRankListResponse
	18, // 12: AgeCompareRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	19, // 13: AgeCompareRequest.compare:type_name -> PassedCompareTimeSpanV4Request
	17, // 14: AgeCompareSummaryResponse.total:type_name -> AgeCompareSummaryTotal
	3,  // 15: AgeCompareSummaryResponse.list:type_name -> AgeSummaryList
	3,  // 16: AgeCompareSummaryResponse.compareList:type_name -> AgeSummaryList
	1,  // 17: PortraitService.AgeSummary:input_type -> AgeRequest
	0,  // 18: PortraitService.Fellow:input_type -> FellowRequest
	0,  // 19: PortraitService.PaymentMethod:input_type -> FellowRequest
	9,  // 20: PortraitService.CityRank:input_type -> CityRankRequest
	12, // 21: PortraitService.ProvinceRank:input_type -> ProvinceRankRequest
	15, // 22: PortraitService.AgeCompareSummary:input_type -> AgeCompareRequest
	2,  // 23: PortraitService.AgeSummary:output_type -> AgeSummaryResponse
	6,  // 24: PortraitService.Fellow:output_type -> FellowResponse
	8,  // 25: PortraitService.PaymentMethod:output_type -> PaymentMethodResponse
	11, // 26: PortraitService.CityRank:output_type -> CityRankResponse
	14, // 27: PortraitService.ProvinceRank:output_type -> ProvinceRankResponse
	16, // 28: PortraitService.AgeCompareSummary:output_type -> AgeCompareSummaryResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_cmd_odas_grpc_portrait_portrait_proto_init() }
func file_cmd_odas_grpc_portrait_portrait_proto_init() {
	if File_cmd_odas_grpc_portrait_portrait_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FellowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeSummaryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeSummaryTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FellowListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FellowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentMethodListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentMethodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityRankRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityRankListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityRankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvinceRankRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvinceRankListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvinceRankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeCompareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeCompareSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_portrait_portrait_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeCompareSummaryTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_odas_grpc_portrait_portrait_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_odas_grpc_portrait_portrait_proto_goTypes,
		DependencyIndexes: file_cmd_odas_grpc_portrait_portrait_proto_depIdxs,
		MessageInfos:      file_cmd_odas_grpc_portrait_portrait_proto_msgTypes,
	}.Build()
	File_cmd_odas_grpc_portrait_portrait_proto = out.File
	file_cmd_odas_grpc_portrait_portrait_proto_rawDesc = nil
	file_cmd_odas_grpc_portrait_portrait_proto_goTypes = nil
	file_cmd_odas_grpc_portrait_portrait_proto_depIdxs = nil
}
