// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: cmd/odas/grpc/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	grpc "odas/cmd/odas/grpc"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义StartEndRequest消息
type RankRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit   int64                                    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RankRequest) Reset() {
	*x = RankRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankRequest) ProtoMessage() {}

func (x *RankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankRequest.ProtoReflect.Descriptor instead.
func (*RankRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *RankRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RankRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 定义 RankBySidResponse 响应
type RankResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*RankListResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RankResponse) Reset() {
	*x = RankResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResponse) ProtoMessage() {}

func (x *RankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResponse.ProtoReflect.Descriptor instead.
func (*RankResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *RankResponse) GetList() []*RankListResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type RankListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId   int64   `protobuf:"varint,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	TicketName string  `protobuf:"bytes,2,opt,name=ticketName,proto3" json:"ticketName,omitempty"`
	Count      int64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Amount     int64   `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Rate       float64 `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *RankListResponse) Reset() {
	*x = RankListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankListResponse) ProtoMessage() {}

func (x *RankListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankListResponse.ProtoReflect.Descriptor instead.
func (*RankListResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *RankListResponse) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *RankListResponse) GetTicketName() string {
	if x != nil {
		return x.TicketName
	}
	return ""
}

func (x *RankListResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RankListResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RankListResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// 定义TicketListBySid请求参数和响应
type ProductTicketListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Compare  *grpc.PassedCompareTimeSpanV4Request     `protobuf:"bytes,2,opt,name=compare,proto3" json:"compare,omitempty"`
	Page     int64                                    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64                                    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *ProductTicketListRequest) Reset() {
	*x = ProductTicketListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductTicketListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductTicketListRequest) ProtoMessage() {}

func (x *ProductTicketListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductTicketListRequest.ProtoReflect.Descriptor instead.
func (*ProductTicketListRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductTicketListRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ProductTicketListRequest) GetCompare() *grpc.PassedCompareTimeSpanV4Request {
	if x != nil {
		return x.Compare
	}
	return nil
}

func (x *ProductTicketListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ProductTicketListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ProductTicketListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List       []*TicketList    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Pagination *grpc.Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *ProductTicketListResponse) Reset() {
	*x = ProductTicketListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductTicketListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductTicketListResponse) ProtoMessage() {}

func (x *ProductTicketListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductTicketListResponse.ProtoReflect.Descriptor instead.
func (*ProductTicketListResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductTicketListResponse) GetList() []*TicketList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ProductTicketListResponse) GetPagination() *grpc.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type TicketList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId          int64   `protobuf:"varint,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	TicketName        string  `protobuf:"bytes,2,opt,name=ticketName,proto3" json:"ticketName,omitempty"`
	Count             int64   `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	CompareCountRate  float64 `protobuf:"fixed64,4,opt,name=CompareCountRate,proto3" json:"CompareCountRate,omitempty"`
	Amount            int64   `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	CompareAmountRate float64 `protobuf:"fixed64,6,opt,name=CompareAmountRate,proto3" json:"CompareAmountRate,omitempty"`
}

func (x *TicketList) Reset() {
	*x = TicketList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketList) ProtoMessage() {}

func (x *TicketList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketList.ProtoReflect.Descriptor instead.
func (*TicketList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *TicketList) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *TicketList) GetTicketName() string {
	if x != nil {
		return x.TicketName
	}
	return ""
}

func (x *TicketList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TicketList) GetCompareCountRate() float64 {
	if x != nil {
		return x.CompareCountRate
	}
	return 0
}

func (x *TicketList) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TicketList) GetCompareAmountRate() float64 {
	if x != nil {
		return x.CompareAmountRate
	}
	return 0
}

// 定义 SalesDetail 请求参数
type SalesDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *grpc.PassedTimeSpanV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	TicketId []int64                       `protobuf:"varint,2,rep,packed,name=ticketId,proto3" json:"ticketId,omitempty"`
}

func (x *SalesDetailRequest) Reset() {
	*x = SalesDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SalesDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesDetailRequest) ProtoMessage() {}

func (x *SalesDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesDetailRequest.ProtoReflect.Descriptor instead.
func (*SalesDetailRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *SalesDetailRequest) GetRequest() *grpc.PassedTimeSpanV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SalesDetailRequest) GetTicketId() []int64 {
	if x != nil {
		return x.TicketId
	}
	return nil
}

// 定义 SalesDetail 响应体
type SalesDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SalesDetailList []*SalesDetailList `protobuf:"bytes,1,rep,name=salesDetailList,proto3" json:"salesDetailList,omitempty"`
}

func (x *SalesDetailResponse) Reset() {
	*x = SalesDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SalesDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesDetailResponse) ProtoMessage() {}

func (x *SalesDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesDetailResponse.ProtoReflect.Descriptor instead.
func (*SalesDetailResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *SalesDetailResponse) GetSalesDetailList() []*SalesDetailList {
	if x != nil {
		return x.SalesDetailList
	}
	return nil
}

type SalesDetailList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId    int64          `protobuf:"varint,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	AmountTrend []*AmountTrend `protobuf:"bytes,2,rep,name=amountTrend,proto3" json:"amountTrend,omitempty"`
	ChannelList []*ChannelList `protobuf:"bytes,3,rep,name=channelList,proto3" json:"channelList,omitempty"`
}

func (x *SalesDetailList) Reset() {
	*x = SalesDetailList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SalesDetailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesDetailList) ProtoMessage() {}

func (x *SalesDetailList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesDetailList.ProtoReflect.Descriptor instead.
func (*SalesDetailList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{8}
}

func (x *SalesDetailList) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *SalesDetailList) GetAmountTrend() []*AmountTrend {
	if x != nil {
		return x.AmountTrend
	}
	return nil
}

func (x *SalesDetailList) GetChannelList() []*ChannelList {
	if x != nil {
		return x.ChannelList
	}
	return nil
}

type AmountTrend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeRange   string `protobuf:"bytes,1,opt,name=timeRange,proto3" json:"timeRange,omitempty"`
	TicketCount int64  `protobuf:"varint,2,opt,name=ticketCount,proto3" json:"ticketCount,omitempty"`
}

func (x *AmountTrend) Reset() {
	*x = AmountTrend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmountTrend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmountTrend) ProtoMessage() {}

func (x *AmountTrend) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmountTrend.ProtoReflect.Descriptor instead.
func (*AmountTrend) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{9}
}

func (x *AmountTrend) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *AmountTrend) GetTicketCount() int64 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

type ChannelList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelName string  `protobuf:"bytes,1,opt,name=channelName,proto3" json:"channelName,omitempty"`
	TicketCount int64   `protobuf:"varint,2,opt,name=ticketCount,proto3" json:"ticketCount,omitempty"`
	Rate        float64 `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *ChannelList) Reset() {
	*x = ChannelList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelList) ProtoMessage() {}

func (x *ChannelList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_product_product_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelList.ProtoReflect.Descriptor instead.
func (*ChannelList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_product_product_proto_rawDescGZIP(), []int{10}
}

func (x *ChannelList) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *ChannelList) GetTicketCount() int64 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

func (x *ChannelList) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_cmd_odas_grpc_product_product_proto protoreflect.FileDescriptor

var file_cmd_odas_grpc_product_product_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x62, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70,
	0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x35, 0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x90, 0x01, 0x0a,
	0x10, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22,
	0xc4, 0x01, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x50, 0x61, 0x73, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x50,
	0x61, 0x73, 0x73, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x70, 0x61, 0x6e, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x69, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xd0, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x61, 0x74, 0x65, 0x22, 0x64, 0x0a, 0x12, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x50, 0x61,
	0x73, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x56, 0x34, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x13, 0x53, 0x61,
	0x6c, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3a, 0x0a, 0x0f, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x61, 0x6c,
	0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0f, 0x73, 0x61,
	0x6c, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x8d, 0x01,
	0x0a, 0x0f, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a,
	0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64,
	0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x12, 0x2e, 0x0a,
	0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4d, 0x0a,
	0x0b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x65, 0x0a, 0x0b,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x32, 0xba, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x0c,
	0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x52,
	0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a,
	0x0a, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x13, 0x2e, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x53, 0x61, 0x6c, 0x65, 0x73,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x24, 0x5a, 0x22, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61,
	0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x3b, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_odas_grpc_product_product_proto_rawDescOnce sync.Once
	file_cmd_odas_grpc_product_product_proto_rawDescData = file_cmd_odas_grpc_product_product_proto_rawDesc
)

func file_cmd_odas_grpc_product_product_proto_rawDescGZIP() []byte {
	file_cmd_odas_grpc_product_product_proto_rawDescOnce.Do(func() {
		file_cmd_odas_grpc_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_odas_grpc_product_product_proto_rawDescData)
	})
	return file_cmd_odas_grpc_product_product_proto_rawDescData
}

var file_cmd_odas_grpc_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cmd_odas_grpc_product_product_proto_goTypes = []interface{}{
	(*RankRequest)(nil),                             // 0: RankRequest
	(*RankResponse)(nil),                            // 1: RankResponse
	(*RankListResponse)(nil),                        // 2: RankListResponse
	(*ProductTicketListRequest)(nil),                // 3: ProductTicketListRequest
	(*ProductTicketListResponse)(nil),               // 4: ProductTicketListResponse
	(*TicketList)(nil),                              // 5: TicketList
	(*SalesDetailRequest)(nil),                      // 6: SalesDetailRequest
	(*SalesDetailResponse)(nil),                     // 7: SalesDetailResponse
	(*SalesDetailList)(nil),                         // 8: SalesDetailList
	(*AmountTrend)(nil),                             // 9: AmountTrend
	(*ChannelList)(nil),                             // 10: ChannelList
	(*grpc.PassedTimeSpanByOrderTypeV4Request)(nil), // 11: PassedTimeSpanByOrderTypeV4Request
	(*grpc.PassedCompareTimeSpanV4Request)(nil),     // 12: PassedCompareTimeSpanV4Request
	(*grpc.Pagination)(nil),                         // 13: Pagination
	(*grpc.PassedTimeSpanV4Request)(nil),            // 14: PassedTimeSpanV4Request
}
var file_cmd_odas_grpc_product_product_proto_depIdxs = []int32{
	11, // 0: RankRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	2,  // 1: RankResponse.list:type_name -> RankListResponse
	11, // 2: ProductTicketListRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	12, // 3: ProductTicketListRequest.compare:type_name -> PassedCompareTimeSpanV4Request
	5,  // 4: ProductTicketListResponse.list:type_name -> TicketList
	13, // 5: ProductTicketListResponse.pagination:type_name -> Pagination
	14, // 6: SalesDetailRequest.request:type_name -> PassedTimeSpanV4Request
	8,  // 7: SalesDetailResponse.salesDetailList:type_name -> SalesDetailList
	9,  // 8: SalesDetailList.amountTrend:type_name -> AmountTrend
	10, // 9: SalesDetailList.channelList:type_name -> ChannelList
	0,  // 10: ProductService.Rank:input_type -> RankRequest
	3,  // 11: ProductService.TicketList:input_type -> ProductTicketListRequest
	6,  // 12: ProductService.SalesDetail:input_type -> SalesDetailRequest
	1,  // 13: ProductService.Rank:output_type -> RankResponse
	4,  // 14: ProductService.TicketList:output_type -> ProductTicketListResponse
	7,  // 15: ProductService.SalesDetail:output_type -> SalesDetailResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cmd_odas_grpc_product_product_proto_init() }
func file_cmd_odas_grpc_product_product_proto_init() {
	if File_cmd_odas_grpc_product_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_odas_grpc_product_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductTicketListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductTicketListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SalesDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SalesDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SalesDetailList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AmountTrend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_product_product_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_odas_grpc_product_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_odas_grpc_product_product_proto_goTypes,
		DependencyIndexes: file_cmd_odas_grpc_product_product_proto_depIdxs,
		MessageInfos:      file_cmd_odas_grpc_product_product_proto_msgTypes,
	}.Build()
	File_cmd_odas_grpc_product_product_proto = out.File
	file_cmd_odas_grpc_product_product_proto_rawDesc = nil
	file_cmd_odas_grpc_product_product_proto_goTypes = nil
	file_cmd_odas_grpc_product_product_proto_depIdxs = nil
}
