// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: cmd/odas/grpc/temporary_booking/temporary_booking.proto

package temporary_booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义summary的请求参数和响应
type TemporaryBookingSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid int64 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *TemporaryBookingSummaryRequest) Reset() {
	*x = TemporaryBookingSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemporaryBookingSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryBookingSummaryRequest) ProtoMessage() {}

func (x *TemporaryBookingSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryBookingSummaryRequest.ProtoReflect.Descriptor instead.
func (*TemporaryBookingSummaryRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescGZIP(), []int{0}
}

func (x *TemporaryBookingSummaryRequest) GetSid() int64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

type TemporaryBookingSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *TemporaryBookingSummaryTotal  `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*TemporaryBookingSummaryList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TemporaryBookingSummaryResponse) Reset() {
	*x = TemporaryBookingSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemporaryBookingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryBookingSummaryResponse) ProtoMessage() {}

func (x *TemporaryBookingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryBookingSummaryResponse.ProtoReflect.Descriptor instead.
func (*TemporaryBookingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescGZIP(), []int{1}
}

func (x *TemporaryBookingSummaryResponse) GetTotal() *TemporaryBookingSummaryTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *TemporaryBookingSummaryResponse) GetList() []*TemporaryBookingSummaryList {
	if x != nil {
		return x.List
	}
	return nil
}

type TemporaryBookingSummaryTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temp    int64 `protobuf:"varint,1,opt,name=temp,proto3" json:"temp,omitempty"`
	Booking int64 `protobuf:"varint,2,opt,name=booking,proto3" json:"booking,omitempty"`
}

func (x *TemporaryBookingSummaryTotal) Reset() {
	*x = TemporaryBookingSummaryTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemporaryBookingSummaryTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryBookingSummaryTotal) ProtoMessage() {}

func (x *TemporaryBookingSummaryTotal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryBookingSummaryTotal.ProtoReflect.Descriptor instead.
func (*TemporaryBookingSummaryTotal) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescGZIP(), []int{2}
}

func (x *TemporaryBookingSummaryTotal) GetTemp() int64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *TemporaryBookingSummaryTotal) GetBooking() int64 {
	if x != nil {
		return x.Booking
	}
	return 0
}

type TemporaryBookingSummaryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Temp    int64  `protobuf:"varint,2,opt,name=temp,proto3" json:"temp,omitempty"`
	Booking int64  `protobuf:"varint,3,opt,name=booking,proto3" json:"booking,omitempty"`
}

func (x *TemporaryBookingSummaryList) Reset() {
	*x = TemporaryBookingSummaryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemporaryBookingSummaryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryBookingSummaryList) ProtoMessage() {}

func (x *TemporaryBookingSummaryList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryBookingSummaryList.ProtoReflect.Descriptor instead.
func (*TemporaryBookingSummaryList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescGZIP(), []int{3}
}

func (x *TemporaryBookingSummaryList) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *TemporaryBookingSummaryList) GetTemp() int64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *TemporaryBookingSummaryList) GetBooking() int64 {
	if x != nil {
		return x.Booking
	}
	return 0
}

var File_cmd_odas_grpc_temporary_booking_temporary_booking_proto protoreflect.FileDescriptor

var file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDesc = []byte{
	0x0a, 0x37, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x1e, 0x54, 0x65, 0x6d,
	0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x88, 0x01,
	0x0a, 0x1f, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x42, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79,
	0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x1c, 0x54, 0x65, 0x6d, 0x70,
	0x6f, 0x72, 0x61, 0x72, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x5f, 0x0a, 0x1b, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72,
	0x61, 0x72, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x32, 0x80, 0x01, 0x0a, 0x17, 0x54, 0x65, 0x6d, 0x70,
	0x6f, 0x72, 0x61, 0x72, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x1e, 0x4c, 0x61, 0x73, 0x74, 0x44, 0x61, 0x79, 0x54, 0x65,
	0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72,
	0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61,
	0x72, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x6f, 0x64,
	0x61, 0x73, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x3b, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescOnce sync.Once
	file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescData = file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDesc
)

func file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescGZIP() []byte {
	file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescOnce.Do(func() {
		file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescData)
	})
	return file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDescData
}

var file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_goTypes = []interface{}{
	(*TemporaryBookingSummaryRequest)(nil),  // 0: TemporaryBookingSummaryRequest
	(*TemporaryBookingSummaryResponse)(nil), // 1: TemporaryBookingSummaryResponse
	(*TemporaryBookingSummaryTotal)(nil),    // 2: TemporaryBookingSummaryTotal
	(*TemporaryBookingSummaryList)(nil),     // 3: TemporaryBookingSummaryList
}
var file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_depIdxs = []int32{
	2, // 0: TemporaryBookingSummaryResponse.total:type_name -> TemporaryBookingSummaryTotal
	3, // 1: TemporaryBookingSummaryResponse.list:type_name -> TemporaryBookingSummaryList
	0, // 2: TemporaryBookingService.LastDayTemporaryBookingSummary:input_type -> TemporaryBookingSummaryRequest
	1, // 3: TemporaryBookingService.LastDayTemporaryBookingSummary:output_type -> TemporaryBookingSummaryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_init() }
func file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_init() {
	if File_cmd_odas_grpc_temporary_booking_temporary_booking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemporaryBookingSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemporaryBookingSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemporaryBookingSummaryTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemporaryBookingSummaryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_goTypes,
		DependencyIndexes: file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_depIdxs,
		MessageInfos:      file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_msgTypes,
	}.Build()
	File_cmd_odas_grpc_temporary_booking_temporary_booking_proto = out.File
	file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_rawDesc = nil
	file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_goTypes = nil
	file_cmd_odas_grpc_temporary_booking_temporary_booking_proto_depIdxs = nil
}
