// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: cmd/odas/grpc/park/park.proto

package park

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义 SpaceRequest 消息
type SpaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 字段
	Sid []int64 `protobuf:"varint,1,rep,packed,name=sid,proto3" json:"sid,omitempty"`
}

func (x *SpaceRequest) Reset() {
	*x = SpaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceRequest) ProtoMessage() {}

func (x *SpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceRequest.ProtoReflect.Descriptor instead.
func (*SpaceRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{0}
}

func (x *SpaceRequest) GetSid() []int64 {
	if x != nil {
		return x.Sid
	}
	return nil
}

// 定义 SpaceResponse 消息返回格式
type SpaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary *SpaceTotal  `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	List    []*SpaceList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SpaceResponse) Reset() {
	*x = SpaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceResponse) ProtoMessage() {}

func (x *SpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceResponse.ProtoReflect.Descriptor instead.
func (*SpaceResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceResponse) GetSummary() *SpaceTotal {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *SpaceResponse) GetList() []*SpaceList {
	if x != nil {
		return x.List
	}
	return nil
}

type SpaceTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Remain int64 `protobuf:"varint,2,opt,name=remain,proto3" json:"remain,omitempty"`
	Used   int64 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
}

func (x *SpaceTotal) Reset() {
	*x = SpaceTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceTotal) ProtoMessage() {}

func (x *SpaceTotal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceTotal.ProtoReflect.Descriptor instead.
func (*SpaceTotal) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{2}
}

func (x *SpaceTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SpaceTotal) GetRemain() int64 {
	if x != nil {
		return x.Remain
	}
	return 0
}

func (x *SpaceTotal) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

type SpaceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BindId int64  `protobuf:"varint,1,opt,name=bindId,proto3" json:"bindId,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Total  int64  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Remain int64  `protobuf:"varint,4,opt,name=remain,proto3" json:"remain,omitempty"`
	Used   int64  `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
}

func (x *SpaceList) Reset() {
	*x = SpaceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceList) ProtoMessage() {}

func (x *SpaceList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceList.ProtoReflect.Descriptor instead.
func (*SpaceList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{3}
}

func (x *SpaceList) GetBindId() int64 {
	if x != nil {
		return x.BindId
	}
	return 0
}

func (x *SpaceList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpaceList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SpaceList) GetRemain() int64 {
	if x != nil {
		return x.Remain
	}
	return 0
}

func (x *SpaceList) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

// 定义 InoutByHourRequest 消息
type InoutByHourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 字段
	Sid []int64 `protobuf:"varint,1,rep,packed,name=sid,proto3" json:"sid,omitempty"`
}

func (x *InoutByHourRequest) Reset() {
	*x = InoutByHourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutByHourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutByHourRequest) ProtoMessage() {}

func (x *InoutByHourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutByHourRequest.ProtoReflect.Descriptor instead.
func (*InoutByHourRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{4}
}

func (x *InoutByHourRequest) GetSid() []int64 {
	if x != nil {
		return x.Sid
	}
	return nil
}

// 定义 InoutByHourResponse 消息返回格式
type InoutByHourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *InoutByHourTotal  `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*InoutByHourList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *InoutByHourResponse) Reset() {
	*x = InoutByHourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutByHourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutByHourResponse) ProtoMessage() {}

func (x *InoutByHourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutByHourResponse.ProtoReflect.Descriptor instead.
func (*InoutByHourResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{5}
}

func (x *InoutByHourResponse) GetTotal() *InoutByHourTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *InoutByHourResponse) GetList() []*InoutByHourList {
	if x != nil {
		return x.List
	}
	return nil
}

type InoutByHourTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In    int64 `protobuf:"varint,1,opt,name=in,proto3" json:"in,omitempty"`
	Out   int64 `protobuf:"varint,2,opt,name=out,proto3" json:"out,omitempty"`
	Being int64 `protobuf:"varint,3,opt,name=being,proto3" json:"being,omitempty"`
}

func (x *InoutByHourTotal) Reset() {
	*x = InoutByHourTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutByHourTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutByHourTotal) ProtoMessage() {}

func (x *InoutByHourTotal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutByHourTotal.ProtoReflect.Descriptor instead.
func (*InoutByHourTotal) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{6}
}

func (x *InoutByHourTotal) GetIn() int64 {
	if x != nil {
		return x.In
	}
	return 0
}

func (x *InoutByHourTotal) GetOut() int64 {
	if x != nil {
		return x.Out
	}
	return 0
}

func (x *InoutByHourTotal) GetBeing() int64 {
	if x != nil {
		return x.Being
	}
	return 0
}

type InoutByHourList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time  string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	In    int64  `protobuf:"varint,2,opt,name=in,proto3" json:"in,omitempty"`
	Out   int64  `protobuf:"varint,3,opt,name=out,proto3" json:"out,omitempty"`
	Being int64  `protobuf:"varint,4,opt,name=being,proto3" json:"being,omitempty"`
}

func (x *InoutByHourList) Reset() {
	*x = InoutByHourList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutByHourList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutByHourList) ProtoMessage() {}

func (x *InoutByHourList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutByHourList.ProtoReflect.Descriptor instead.
func (*InoutByHourList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{7}
}

func (x *InoutByHourList) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *InoutByHourList) GetIn() int64 {
	if x != nil {
		return x.In
	}
	return 0
}

func (x *InoutByHourList) GetOut() int64 {
	if x != nil {
		return x.Out
	}
	return 0
}

func (x *InoutByHourList) GetBeing() int64 {
	if x != nil {
		return x.Being
	}
	return 0
}

// 定义 InoutByLocationRequest 消息
type InoutByLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 字段
	Sid      []int64                `protobuf:"varint,1,rep,packed,name=sid,proto3" json:"sid,omitempty"`
	Start    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Province string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	Unknown  bool                   `protobuf:"varint,5,opt,name=unknown,proto3" json:"unknown,omitempty"`
	Limit    int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *InoutByLocationRequest) Reset() {
	*x = InoutByLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutByLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutByLocationRequest) ProtoMessage() {}

func (x *InoutByLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutByLocationRequest.ProtoReflect.Descriptor instead.
func (*InoutByLocationRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{8}
}

func (x *InoutByLocationRequest) GetSid() []int64 {
	if x != nil {
		return x.Sid
	}
	return nil
}

func (x *InoutByLocationRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *InoutByLocationRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *InoutByLocationRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *InoutByLocationRequest) GetUnknown() bool {
	if x != nil {
		return x.Unknown
	}
	return false
}

func (x *InoutByLocationRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 定义 InoutByLocationResponse 消息返回格式
type InoutByLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary     *InoutByLocationTotal `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	InsideList  []*InoutSideParkList  `protobuf:"bytes,2,rep,name=insideList,proto3" json:"insideList,omitempty"`
	OutsideList []*InoutSideParkList  `protobuf:"bytes,3,rep,name=outsideList,proto3" json:"outsideList,omitempty"`
}

func (x *InoutByLocationResponse) Reset() {
	*x = InoutByLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutByLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutByLocationResponse) ProtoMessage() {}

func (x *InoutByLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutByLocationResponse.ProtoReflect.Descriptor instead.
func (*InoutByLocationResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{9}
}

func (x *InoutByLocationResponse) GetSummary() *InoutByLocationTotal {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *InoutByLocationResponse) GetInsideList() []*InoutSideParkList {
	if x != nil {
		return x.InsideList
	}
	return nil
}

func (x *InoutByLocationResponse) GetOutsideList() []*InoutSideParkList {
	if x != nil {
		return x.OutsideList
	}
	return nil
}

type InoutByLocationTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total          int64   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	OutsideTotal   int64   `protobuf:"varint,2,opt,name=outsideTotal,proto3" json:"outsideTotal,omitempty"`
	OutsidePercent float64 `protobuf:"fixed64,3,opt,name=outsidePercent,proto3" json:"outsidePercent,omitempty"`
	InsideTotal    int64   `protobuf:"varint,4,opt,name=insideTotal,proto3" json:"insideTotal,omitempty"`
	InsidePercent  float64 `protobuf:"fixed64,5,opt,name=insidePercent,proto3" json:"insidePercent,omitempty"`
}

func (x *InoutByLocationTotal) Reset() {
	*x = InoutByLocationTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutByLocationTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutByLocationTotal) ProtoMessage() {}

func (x *InoutByLocationTotal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutByLocationTotal.ProtoReflect.Descriptor instead.
func (*InoutByLocationTotal) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{10}
}

func (x *InoutByLocationTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *InoutByLocationTotal) GetOutsideTotal() int64 {
	if x != nil {
		return x.OutsideTotal
	}
	return 0
}

func (x *InoutByLocationTotal) GetOutsidePercent() float64 {
	if x != nil {
		return x.OutsidePercent
	}
	return 0
}

func (x *InoutByLocationTotal) GetInsideTotal() int64 {
	if x != nil {
		return x.InsideTotal
	}
	return 0
}

func (x *InoutByLocationTotal) GetInsidePercent() float64 {
	if x != nil {
		return x.InsidePercent
	}
	return 0
}

type InoutSideParkList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string  `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Count    int64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Rate     float32 `protobuf:"fixed32,3,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *InoutSideParkList) Reset() {
	*x = InoutSideParkList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutSideParkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutSideParkList) ProtoMessage() {}

func (x *InoutSideParkList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutSideParkList.ProtoReflect.Descriptor instead.
func (*InoutSideParkList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{11}
}

func (x *InoutSideParkList) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *InoutSideParkList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *InoutSideParkList) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// 定义 InoutByHourRequest 消息
type InoutCompareByHourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 字段
	Sid  []int64                `protobuf:"varint,1,rep,packed,name=sid,proto3" json:"sid,omitempty"`
	Date *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *InoutCompareByHourRequest) Reset() {
	*x = InoutCompareByHourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutCompareByHourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutCompareByHourRequest) ProtoMessage() {}

func (x *InoutCompareByHourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutCompareByHourRequest.ProtoReflect.Descriptor instead.
func (*InoutCompareByHourRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{12}
}

func (x *InoutCompareByHourRequest) GetSid() []int64 {
	if x != nil {
		return x.Sid
	}
	return nil
}

func (x *InoutCompareByHourRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// 定义 InoutCompareByHourResponse 消息返回格式
type InoutCompareByHourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total       *InoutCompareByHourTotal `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	List        []*InoutByHourList       `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	CompareList []*InoutByHourList       `protobuf:"bytes,3,rep,name=compareList,proto3" json:"compareList,omitempty"`
}

func (x *InoutCompareByHourResponse) Reset() {
	*x = InoutCompareByHourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutCompareByHourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutCompareByHourResponse) ProtoMessage() {}

func (x *InoutCompareByHourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutCompareByHourResponse.ProtoReflect.Descriptor instead.
func (*InoutCompareByHourResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{13}
}

func (x *InoutCompareByHourResponse) GetTotal() *InoutCompareByHourTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *InoutCompareByHourResponse) GetList() []*InoutByHourList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *InoutCompareByHourResponse) GetCompareList() []*InoutByHourList {
	if x != nil {
		return x.CompareList
	}
	return nil
}

type InoutCompareByHourTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In           int64 `protobuf:"varint,1,opt,name=in,proto3" json:"in,omitempty"`
	Out          int64 `protobuf:"varint,2,opt,name=out,proto3" json:"out,omitempty"`
	Being        int64 `protobuf:"varint,3,opt,name=being,proto3" json:"being,omitempty"`
	CompareIn    int64 `protobuf:"varint,4,opt,name=compareIn,proto3" json:"compareIn,omitempty"`
	CompareOut   int64 `protobuf:"varint,5,opt,name=compareOut,proto3" json:"compareOut,omitempty"`
	CompareBeing int64 `protobuf:"varint,6,opt,name=compareBeing,proto3" json:"compareBeing,omitempty"`
}

func (x *InoutCompareByHourTotal) Reset() {
	*x = InoutCompareByHourTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InoutCompareByHourTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InoutCompareByHourTotal) ProtoMessage() {}

func (x *InoutCompareByHourTotal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_park_park_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InoutCompareByHourTotal.ProtoReflect.Descriptor instead.
func (*InoutCompareByHourTotal) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_park_park_proto_rawDescGZIP(), []int{14}
}

func (x *InoutCompareByHourTotal) GetIn() int64 {
	if x != nil {
		return x.In
	}
	return 0
}

func (x *InoutCompareByHourTotal) GetOut() int64 {
	if x != nil {
		return x.Out
	}
	return 0
}

func (x *InoutCompareByHourTotal) GetBeing() int64 {
	if x != nil {
		return x.Being
	}
	return 0
}

func (x *InoutCompareByHourTotal) GetCompareIn() int64 {
	if x != nil {
		return x.CompareIn
	}
	return 0
}

func (x *InoutCompareByHourTotal) GetCompareOut() int64 {
	if x != nil {
		return x.CompareOut
	}
	return 0
}

func (x *InoutCompareByHourTotal) GetCompareBeing() int64 {
	if x != nil {
		return x.CompareBeing
	}
	return 0
}

var File_cmd_odas_grpc_park_park_proto protoreflect.FileDescriptor

var file_cmd_odas_grpc_park_park_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x20, 0x0a, 0x0c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x73,
	0x69, 0x64, 0x22, 0x56, 0x0a, 0x0d, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x0a, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x22, 0x79, 0x0a, 0x09, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x64, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x64, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x64, 0x22, 0x26, 0x0a, 0x12, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79,
	0x48, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x64, 0x0a,
	0x13, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x75,
	0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x24, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x6e,
	0x6f, 0x75, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x10, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x48, 0x6f,
	0x75, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x69,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x65, 0x69, 0x6e, 0x67, 0x22,
	0x5d, 0x0a, 0x0f, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x69, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x65, 0x69, 0x6e, 0x67, 0x22, 0xd6,
	0x01, 0x0a, 0x16, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2c, 0x0a,
	0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x17, 0x49, 0x6e, 0x6f, 0x75,
	0x74, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x07, 0x73, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x12, 0x32, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74,
	0x53, 0x69, 0x64, 0x65, 0x50, 0x61, 0x72, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0a, 0x69, 0x6e,
	0x73, 0x69, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x73,
	0x69, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x49, 0x6e, 0x6f, 0x75, 0x74, 0x53, 0x69, 0x64, 0x65, 0x50, 0x61, 0x72, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xc0,
	0x01, 0x0a, 0x14, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x22, 0x0a,
	0x0c, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x6f, 0x75, 0x74, 0x73, 0x69,
	0x64, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73,
	0x69, 0x64, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x69, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x69,
	0x6e, 0x73, 0x69, 0x64, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x22, 0x59, 0x0a, 0x11, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x53, 0x69, 0x64, 0x65, 0x50, 0x61,
	0x72, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x5d, 0x0a, 0x19,
	0x49, 0x6e, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x48, 0x6f,
	0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x1a,
	0x49, 0x6e, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x48, 0x6f,
	0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x49, 0x6e, 0x6f, 0x75,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74,
	0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x48,
	0x6f, 0x75, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0xb3, 0x01, 0x0a, 0x17, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f,
	0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x62, 0x65, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x65, 0x49, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x4f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x42, 0x65, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x65, 0x69, 0x6e, 0x67, 0x32, 0x8c, 0x02, 0x0a, 0x0b, 0x50,
	0x61, 0x72, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x0d, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x48,
	0x6f, 0x75, 0x72, 0x12, 0x13, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x75,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74,
	0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x46, 0x0a, 0x0f, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x49,
	0x6e, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x12, 0x49, 0x6e, 0x6f, 0x75,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x1a,
	0x2e, 0x49, 0x6e, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x48,
	0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x49, 0x6e, 0x6f,
	0x75, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x42, 0x79, 0x48, 0x6f, 0x75, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x6f, 0x64, 0x61,
	0x73, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x61, 0x72, 0x6b, 0x3b, 0x70, 0x61, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cmd_odas_grpc_park_park_proto_rawDescOnce sync.Once
	file_cmd_odas_grpc_park_park_proto_rawDescData = file_cmd_odas_grpc_park_park_proto_rawDesc
)

func file_cmd_odas_grpc_park_park_proto_rawDescGZIP() []byte {
	file_cmd_odas_grpc_park_park_proto_rawDescOnce.Do(func() {
		file_cmd_odas_grpc_park_park_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_odas_grpc_park_park_proto_rawDescData)
	})
	return file_cmd_odas_grpc_park_park_proto_rawDescData
}

var file_cmd_odas_grpc_park_park_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cmd_odas_grpc_park_park_proto_goTypes = []interface{}{
	(*SpaceRequest)(nil),               // 0: SpaceRequest
	(*SpaceResponse)(nil),              // 1: SpaceResponse
	(*SpaceTotal)(nil),                 // 2: SpaceTotal
	(*SpaceList)(nil),                  // 3: SpaceList
	(*InoutByHourRequest)(nil),         // 4: InoutByHourRequest
	(*InoutByHourResponse)(nil),        // 5: InoutByHourResponse
	(*InoutByHourTotal)(nil),           // 6: InoutByHourTotal
	(*InoutByHourList)(nil),            // 7: InoutByHourList
	(*InoutByLocationRequest)(nil),     // 8: InoutByLocationRequest
	(*InoutByLocationResponse)(nil),    // 9: InoutByLocationResponse
	(*InoutByLocationTotal)(nil),       // 10: InoutByLocationTotal
	(*InoutSideParkList)(nil),          // 11: InoutSideParkList
	(*InoutCompareByHourRequest)(nil),  // 12: InoutCompareByHourRequest
	(*InoutCompareByHourResponse)(nil), // 13: InoutCompareByHourResponse
	(*InoutCompareByHourTotal)(nil),    // 14: InoutCompareByHourTotal
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
}
var file_cmd_odas_grpc_park_park_proto_depIdxs = []int32{
	2,  // 0: SpaceResponse.summary:type_name -> SpaceTotal
	3,  // 1: SpaceResponse.list:type_name -> SpaceList
	6,  // 2: InoutByHourResponse.total:type_name -> InoutByHourTotal
	7,  // 3: InoutByHourResponse.list:type_name -> InoutByHourList
	15, // 4: InoutByLocationRequest.start:type_name -> google.protobuf.Timestamp
	15, // 5: InoutByLocationRequest.end:type_name -> google.protobuf.Timestamp
	10, // 6: InoutByLocationResponse.summary:type_name -> InoutByLocationTotal
	11, // 7: InoutByLocationResponse.insideList:type_name -> InoutSideParkList
	11, // 8: InoutByLocationResponse.outsideList:type_name -> InoutSideParkList
	15, // 9: InoutCompareByHourRequest.date:type_name -> google.protobuf.Timestamp
	14, // 10: InoutCompareByHourResponse.total:type_name -> InoutCompareByHourTotal
	7,  // 11: InoutCompareByHourResponse.list:type_name -> InoutByHourList
	7,  // 12: InoutCompareByHourResponse.compareList:type_name -> InoutByHourList
	0,  // 13: ParkService.Space:input_type -> SpaceRequest
	4,  // 14: ParkService.InoutByHour:input_type -> InoutByHourRequest
	8,  // 15: ParkService.InoutByLocation:input_type -> InoutByLocationRequest
	12, // 16: ParkService.InoutCompareByHour:input_type -> InoutCompareByHourRequest
	1,  // 17: ParkService.Space:output_type -> SpaceResponse
	5,  // 18: ParkService.InoutByHour:output_type -> InoutByHourResponse
	9,  // 19: ParkService.InoutByLocation:output_type -> InoutByLocationResponse
	13, // 20: ParkService.InoutCompareByHour:output_type -> InoutCompareByHourResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cmd_odas_grpc_park_park_proto_init() }
func file_cmd_odas_grpc_park_park_proto_init() {
	if File_cmd_odas_grpc_park_park_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_odas_grpc_park_park_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutByHourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutByHourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutByHourTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutByHourList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutByLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutByLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutByLocationTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutSideParkList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutCompareByHourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutCompareByHourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_park_park_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InoutCompareByHourTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_odas_grpc_park_park_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_odas_grpc_park_park_proto_goTypes,
		DependencyIndexes: file_cmd_odas_grpc_park_park_proto_depIdxs,
		MessageInfos:      file_cmd_odas_grpc_park_park_proto_msgTypes,
	}.Build()
	File_cmd_odas_grpc_park_park_proto = out.File
	file_cmd_odas_grpc_park_park_proto_rawDesc = nil
	file_cmd_odas_grpc_park_park_proto_goTypes = nil
	file_cmd_odas_grpc_park_park_proto_depIdxs = nil
}
