// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: cmd/odas/grpc/channel/channel.proto

package channel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	grpc "odas/cmd/odas/grpc"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelName string  `protobuf:"bytes,1,opt,name=channelName,proto3" json:"channelName,omitempty"`
	Tickets     int64   `protobuf:"varint,2,opt,name=tickets,proto3" json:"tickets,omitempty"`
	Amount      int64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Rate        float64 `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *ChannelSummary) Reset() {
	*x = ChannelSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSummary) ProtoMessage() {}

func (x *ChannelSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSummary.ProtoReflect.Descriptor instead.
func (*ChannelSummary) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelSummary) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *ChannelSummary) GetTickets() int64 {
	if x != nil {
		return x.Tickets
	}
	return 0
}

func (x *ChannelSummary) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ChannelSummary) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type OrderChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary []*ChannelSummary `protobuf:"bytes,1,rep,name=summary,proto3" json:"summary,omitempty"`
}

func (x *OrderChannelResponse) Reset() {
	*x = OrderChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderChannelResponse) ProtoMessage() {}

func (x *OrderChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderChannelResponse.ProtoReflect.Descriptor instead.
func (*OrderChannelResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{1}
}

func (x *OrderChannelResponse) GetSummary() []*ChannelSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type OrderFullChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit   int64                                    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *OrderFullChannelRequest) Reset() {
	*x = OrderFullChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFullChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFullChannelRequest) ProtoMessage() {}

func (x *OrderFullChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFullChannelRequest.ProtoReflect.Descriptor instead.
func (*OrderFullChannelRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{2}
}

func (x *OrderFullChannelRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *OrderFullChannelRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OrderFullChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *OrderChannelSummary    `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*OrderFullChannelList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *OrderFullChannelResponse) Reset() {
	*x = OrderFullChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFullChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFullChannelResponse) ProtoMessage() {}

func (x *OrderFullChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFullChannelResponse.ProtoReflect.Descriptor instead.
func (*OrderFullChannelResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{3}
}

func (x *OrderFullChannelResponse) GetTotal() *OrderChannelSummary {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *OrderFullChannelResponse) GetList() []*OrderFullChannelList {
	if x != nil {
		return x.List
	}
	return nil
}

type OrderChannelSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderCount  int64 `protobuf:"varint,1,opt,name=orderCount,proto3" json:"orderCount,omitempty"`
	TicketCount int64 `protobuf:"varint,2,opt,name=ticketCount,proto3" json:"ticketCount,omitempty"`
	Amount      int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *OrderChannelSummary) Reset() {
	*x = OrderChannelSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderChannelSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderChannelSummary) ProtoMessage() {}

func (x *OrderChannelSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderChannelSummary.ProtoReflect.Descriptor instead.
func (*OrderChannelSummary) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{4}
}

func (x *OrderChannelSummary) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *OrderChannelSummary) GetTicketCount() int64 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

func (x *OrderChannelSummary) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ChannelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelClassId   int64  `protobuf:"varint,1,opt,name=channelClassId,proto3" json:"channelClassId,omitempty"`
	ChannelClassName string `protobuf:"bytes,2,opt,name=channelClassName,proto3" json:"channelClassName,omitempty"`
}

func (x *ChannelData) Reset() {
	*x = ChannelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelData) ProtoMessage() {}

func (x *ChannelData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelData.ProtoReflect.Descriptor instead.
func (*ChannelData) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelData) GetChannelClassId() int64 {
	if x != nil {
		return x.ChannelClassId
	}
	return 0
}

func (x *ChannelData) GetChannelClassName() string {
	if x != nil {
		return x.ChannelClassName
	}
	return ""
}

type OrderFullChannelList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel *ChannelData         `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Summary *OrderChannelSummary `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *OrderFullChannelList) Reset() {
	*x = OrderFullChannelList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFullChannelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFullChannelList) ProtoMessage() {}

func (x *OrderFullChannelList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFullChannelList.ProtoReflect.Descriptor instead.
func (*OrderFullChannelList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{6}
}

func (x *OrderFullChannelList) GetChannel() *ChannelData {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *OrderFullChannelList) GetSummary() *OrderChannelSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type OTAChannelTicketSaleStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request              *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit                int64                                    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ExcludePackageTicket bool                                     `protobuf:"varint,3,opt,name=excludePackageTicket,proto3" json:"excludePackageTicket,omitempty"`
}

func (x *OTAChannelTicketSaleStatRequest) Reset() {
	*x = OTAChannelTicketSaleStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OTAChannelTicketSaleStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTAChannelTicketSaleStatRequest) ProtoMessage() {}

func (x *OTAChannelTicketSaleStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTAChannelTicketSaleStatRequest.ProtoReflect.Descriptor instead.
func (*OTAChannelTicketSaleStatRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{7}
}

func (x *OTAChannelTicketSaleStatRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *OTAChannelTicketSaleStatRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *OTAChannelTicketSaleStatRequest) GetExcludePackageTicket() bool {
	if x != nil {
		return x.ExcludePackageTicket
	}
	return false
}

type OTAChannelTicketSaleStatItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel    *ChannelData         `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	TicketId   int64                `protobuf:"varint,3,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	TicketName string               `protobuf:"bytes,4,opt,name=ticketName,proto3" json:"ticketName,omitempty"`
	Summary    *OrderChannelSummary `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *OTAChannelTicketSaleStatItem) Reset() {
	*x = OTAChannelTicketSaleStatItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OTAChannelTicketSaleStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTAChannelTicketSaleStatItem) ProtoMessage() {}

func (x *OTAChannelTicketSaleStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTAChannelTicketSaleStatItem.ProtoReflect.Descriptor instead.
func (*OTAChannelTicketSaleStatItem) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{8}
}

func (x *OTAChannelTicketSaleStatItem) GetChannel() *ChannelData {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *OTAChannelTicketSaleStatItem) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *OTAChannelTicketSaleStatItem) GetTicketName() string {
	if x != nil {
		return x.TicketName
	}
	return ""
}

func (x *OTAChannelTicketSaleStatItem) GetSummary() *OrderChannelSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type OTAChannelTicketSaleStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*OTAChannelTicketSaleStatItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *OTAChannelTicketSaleStatResponse) Reset() {
	*x = OTAChannelTicketSaleStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OTAChannelTicketSaleStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTAChannelTicketSaleStatResponse) ProtoMessage() {}

func (x *OTAChannelTicketSaleStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTAChannelTicketSaleStatResponse.ProtoReflect.Descriptor instead.
func (*OTAChannelTicketSaleStatResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{9}
}

func (x *OTAChannelTicketSaleStatResponse) GetList() []*OTAChannelTicketSaleStatItem {
	if x != nil {
		return x.List
	}
	return nil
}

type TicketRefundRatioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request     *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	ChannelType int64                                    `protobuf:"varint,2,opt,name=channelType,proto3" json:"channelType,omitempty"`
}

func (x *TicketRefundRatioRequest) Reset() {
	*x = TicketRefundRatioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketRefundRatioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRefundRatioRequest) ProtoMessage() {}

func (x *TicketRefundRatioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRefundRatioRequest.ProtoReflect.Descriptor instead.
func (*TicketRefundRatioRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{10}
}

func (x *TicketRefundRatioRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TicketRefundRatioRequest) GetChannelType() int64 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

type TicketRefundRatioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *TicketRefundRatioTotal  `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*TicketRefundRatioList `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TicketRefundRatioResponse) Reset() {
	*x = TicketRefundRatioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketRefundRatioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRefundRatioResponse) ProtoMessage() {}

func (x *TicketRefundRatioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRefundRatioResponse.ProtoReflect.Descriptor instead.
func (*TicketRefundRatioResponse) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{11}
}

func (x *TicketRefundRatioResponse) GetTotal() *TicketRefundRatioTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *TicketRefundRatioResponse) GetList() []*TicketRefundRatioList {
	if x != nil {
		return x.List
	}
	return nil
}

type TicketRefundRatioTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayTicketNum       int64 `protobuf:"varint,1,opt,name=payTicketNum,proto3" json:"payTicketNum,omitempty"`
	CancelTicketNum    int64 `protobuf:"varint,2,opt,name=cancelTicketNum,proto3" json:"cancelTicketNum,omitempty"`
	RevokeTicketNum    int64 `protobuf:"varint,3,opt,name=revokeTicketNum,proto3" json:"revokeTicketNum,omitempty"`
	AfterSaleTicketNum int64 `protobuf:"varint,4,opt,name=afterSaleTicketNum,proto3" json:"afterSaleTicketNum,omitempty"`
}

func (x *TicketRefundRatioTotal) Reset() {
	*x = TicketRefundRatioTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketRefundRatioTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRefundRatioTotal) ProtoMessage() {}

func (x *TicketRefundRatioTotal) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRefundRatioTotal.ProtoReflect.Descriptor instead.
func (*TicketRefundRatioTotal) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{12}
}

func (x *TicketRefundRatioTotal) GetPayTicketNum() int64 {
	if x != nil {
		return x.PayTicketNum
	}
	return 0
}

func (x *TicketRefundRatioTotal) GetCancelTicketNum() int64 {
	if x != nil {
		return x.CancelTicketNum
	}
	return 0
}

func (x *TicketRefundRatioTotal) GetRevokeTicketNum() int64 {
	if x != nil {
		return x.RevokeTicketNum
	}
	return 0
}

func (x *TicketRefundRatioTotal) GetAfterSaleTicketNum() int64 {
	if x != nil {
		return x.AfterSaleTicketNum
	}
	return 0
}

type TicketRefundRatioList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel *ChannelData            `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Total   *TicketRefundRatioTotal `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *TicketRefundRatioList) Reset() {
	*x = TicketRefundRatioList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketRefundRatioList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRefundRatioList) ProtoMessage() {}

func (x *TicketRefundRatioList) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRefundRatioList.ProtoReflect.Descriptor instead.
func (*TicketRefundRatioList) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{13}
}

func (x *TicketRefundRatioList) GetChannel() *ChannelData {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *TicketRefundRatioList) GetTotal() *TicketRefundRatioTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

type OrderSecondaryChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request        *grpc.PassedTimeSpanByOrderTypeV4Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit          int64                                    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ChannelClassId int64                                    `protobuf:"varint,3,opt,name=channelClassId,proto3" json:"channelClassId,omitempty"`
}

func (x *OrderSecondaryChannelRequest) Reset() {
	*x = OrderSecondaryChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSecondaryChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSecondaryChannelRequest) ProtoMessage() {}

func (x *OrderSecondaryChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_odas_grpc_channel_channel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSecondaryChannelRequest.ProtoReflect.Descriptor instead.
func (*OrderSecondaryChannelRequest) Descriptor() ([]byte, []int) {
	return file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP(), []int{14}
}

func (x *OrderSecondaryChannelRequest) GetRequest() *grpc.PassedTimeSpanByOrderTypeV4Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *OrderSecondaryChannelRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *OrderSecondaryChannelRequest) GetChannelClassId() int64 {
	if x != nil {
		return x.ChannelClassId
	}
	return 0
}

var File_cmd_odas_grpc_channel_channel_proto protoreflect.FileDescriptor

var file_cmd_odas_grpc_channel_channel_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x63, 0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x78, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x41, 0x0a, 0x14, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x6e,
	0x0a, 0x17, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x50, 0x61, 0x73,
	0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x71,
	0x0a, 0x18, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0x6f, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x61, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6e, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x75,
	0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x07, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0xaa, 0x01, 0x0a, 0x1f, 0x4f, 0x54, 0x41, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x50, 0x61, 0x73,
	0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x32,
	0x0a, 0x14, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x65, 0x78,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x22, 0xb2, 0x01, 0x0a, 0x1c, 0x4f, 0x54, 0x41, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x26, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x55, 0x0a, 0x20, 0x4f, 0x54, 0x41, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4f, 0x54, 0x41, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x7b,
	0x0a, 0x18, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x61,
	0x74, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x50, 0x61,
	0x73, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x76, 0x0a, 0x19, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0xc0, 0x01, 0x0a, 0x16, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x22,
	0x0a, 0x0c, 0x70, 0x61, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e,
	0x75, 0x6d, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x28, 0x0a, 0x0f,
	0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x2e, 0x0a, 0x12, 0x61, 0x66, 0x74, 0x65, 0x72, 0x53,
	0x61, 0x6c, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x12, 0x61, 0x66, 0x74, 0x65, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x22, 0x6e, 0x0a, 0x15, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x26, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x2d, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x9b, 0x01, 0x0a, 0x1c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x49, 0x64, 0x32, 0xaf, 0x03, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x23, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x56, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x75,
	0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x61, 0x0a, 0x18, 0x4f, 0x54, 0x41, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x12, 0x20, 0x2e, 0x4f,
	0x54, 0x41, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53,
	0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x4f, 0x54, 0x41, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x53, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x66,
	0x75, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x19, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x53, 0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x61, 0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1d, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x63,
	0x6d, 0x64, 0x2f, 0x6f, 0x64, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x3b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_odas_grpc_channel_channel_proto_rawDescOnce sync.Once
	file_cmd_odas_grpc_channel_channel_proto_rawDescData = file_cmd_odas_grpc_channel_channel_proto_rawDesc
)

func file_cmd_odas_grpc_channel_channel_proto_rawDescGZIP() []byte {
	file_cmd_odas_grpc_channel_channel_proto_rawDescOnce.Do(func() {
		file_cmd_odas_grpc_channel_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_odas_grpc_channel_channel_proto_rawDescData)
	})
	return file_cmd_odas_grpc_channel_channel_proto_rawDescData
}

var file_cmd_odas_grpc_channel_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cmd_odas_grpc_channel_channel_proto_goTypes = []interface{}{
	(*ChannelSummary)(nil),                          // 0: ChannelSummary
	(*OrderChannelResponse)(nil),                    // 1: OrderChannelResponse
	(*OrderFullChannelRequest)(nil),                 // 2: OrderFullChannelRequest
	(*OrderFullChannelResponse)(nil),                // 3: OrderFullChannelResponse
	(*OrderChannelSummary)(nil),                     // 4: OrderChannelSummary
	(*ChannelData)(nil),                             // 5: ChannelData
	(*OrderFullChannelList)(nil),                    // 6: OrderFullChannelList
	(*OTAChannelTicketSaleStatRequest)(nil),         // 7: OTAChannelTicketSaleStatRequest
	(*OTAChannelTicketSaleStatItem)(nil),            // 8: OTAChannelTicketSaleStatItem
	(*OTAChannelTicketSaleStatResponse)(nil),        // 9: OTAChannelTicketSaleStatResponse
	(*TicketRefundRatioRequest)(nil),                // 10: TicketRefundRatioRequest
	(*TicketRefundRatioResponse)(nil),               // 11: TicketRefundRatioResponse
	(*TicketRefundRatioTotal)(nil),                  // 12: TicketRefundRatioTotal
	(*TicketRefundRatioList)(nil),                   // 13: TicketRefundRatioList
	(*OrderSecondaryChannelRequest)(nil),            // 14: OrderSecondaryChannelRequest
	(*grpc.PassedTimeSpanByOrderTypeV4Request)(nil), // 15: PassedTimeSpanByOrderTypeV4Request
}
var file_cmd_odas_grpc_channel_channel_proto_depIdxs = []int32{
	0,  // 0: OrderChannelResponse.summary:type_name -> ChannelSummary
	15, // 1: OrderFullChannelRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	4,  // 2: OrderFullChannelResponse.total:type_name -> OrderChannelSummary
	6,  // 3: OrderFullChannelResponse.list:type_name -> OrderFullChannelList
	5,  // 4: OrderFullChannelList.channel:type_name -> ChannelData
	4,  // 5: OrderFullChannelList.summary:type_name -> OrderChannelSummary
	15, // 6: OTAChannelTicketSaleStatRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	5,  // 7: OTAChannelTicketSaleStatItem.channel:type_name -> ChannelData
	4,  // 8: OTAChannelTicketSaleStatItem.summary:type_name -> OrderChannelSummary
	8,  // 9: OTAChannelTicketSaleStatResponse.list:type_name -> OTAChannelTicketSaleStatItem
	15, // 10: TicketRefundRatioRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	12, // 11: TicketRefundRatioResponse.total:type_name -> TicketRefundRatioTotal
	13, // 12: TicketRefundRatioResponse.list:type_name -> TicketRefundRatioList
	5,  // 13: TicketRefundRatioList.channel:type_name -> ChannelData
	12, // 14: TicketRefundRatioList.total:type_name -> TicketRefundRatioTotal
	15, // 15: OrderSecondaryChannelRequest.request:type_name -> PassedTimeSpanByOrderTypeV4Request
	15, // 16: ChannelService.OrderChannel:input_type -> PassedTimeSpanByOrderTypeV4Request
	2,  // 17: ChannelService.OrderFullChannel:input_type -> OrderFullChannelRequest
	7,  // 18: ChannelService.OTAChannelTicketSaleStat:input_type -> OTAChannelTicketSaleStatRequest
	10, // 19: ChannelService.TicketRefundRatio:input_type -> TicketRefundRatioRequest
	14, // 20: ChannelService.OrderSecondaryChannel:input_type -> OrderSecondaryChannelRequest
	1,  // 21: ChannelService.OrderChannel:output_type -> OrderChannelResponse
	3,  // 22: ChannelService.OrderFullChannel:output_type -> OrderFullChannelResponse
	9,  // 23: ChannelService.OTAChannelTicketSaleStat:output_type -> OTAChannelTicketSaleStatResponse
	11, // 24: ChannelService.TicketRefundRatio:output_type -> TicketRefundRatioResponse
	3,  // 25: ChannelService.OrderSecondaryChannel:output_type -> OrderFullChannelResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_cmd_odas_grpc_channel_channel_proto_init() }
func file_cmd_odas_grpc_channel_channel_proto_init() {
	if File_cmd_odas_grpc_channel_channel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFullChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFullChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderChannelSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFullChannelList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OTAChannelTicketSaleStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OTAChannelTicketSaleStatItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OTAChannelTicketSaleStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketRefundRatioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketRefundRatioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketRefundRatioTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketRefundRatioList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_odas_grpc_channel_channel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSecondaryChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_odas_grpc_channel_channel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_odas_grpc_channel_channel_proto_goTypes,
		DependencyIndexes: file_cmd_odas_grpc_channel_channel_proto_depIdxs,
		MessageInfos:      file_cmd_odas_grpc_channel_channel_proto_msgTypes,
	}.Build()
	File_cmd_odas_grpc_channel_channel_proto = out.File
	file_cmd_odas_grpc_channel_channel_proto_rawDesc = nil
	file_cmd_odas_grpc_channel_channel_proto_goTypes = nil
	file_cmd_odas_grpc_channel_channel_proto_depIdxs = nil
}
